### ISSUE TITLE
Feature Request: Any chance this will be added to the Apple App Store?

### ISSUE THREAD

**Issue by StewAlexander-com** [ProtonVPN/ios-app#2]
For those of us without a developers license, or want to develop code for Apple, is there any chance you all or one of your community will wrap this in a GUI and put it up on Apple's App Store?

**Comment by nopor** [comment]
1. The developer account is free, if you don't want publish anything in the App Store.
2. https://apps.apple.com/us/app/protonvpn-fast-secure-vpn/id1437005085
(edited link)
