### ISSUE TITLE
Most popular

### ISSUE THREAD

**Issue by KovalevArtem** [ProtonVPN/ios-app#8]
Original:
![image](https://user-images.githubusercontent.com/36500228/98254884-dcc9e200-1f8d-11eb-9b1d-ee4631a9d47c.png)

Russian interface:
![655179D4-4012-40AE-82A9-23ED7B3BED77](https://user-images.githubusercontent.com/36500228/98257459-c2453800-1f90-11eb-8939-30172f6d7882.PNG)

I have no ideas on how to change the translation to a shorter one ...

**Comment by jaroslavas** [comment]
Спасибо. 
This was fixed and will be available in upcoming app versions.
